let languageContent = {
    en: {
        title: "Igor Volkov - iOS Developer",
        logo__text: "IV",
        link1: "Projects",
        link2: "About me",
        link3: "Resume",
        link4: "Contact",
        hamb__title: "Menu",
        name__title: "Igor Volkov",
        name__subtitle: "Expanding Horizons: My Path in the World of Mobile and Web Development",
        headline1: "Projects",
        tab1: "Swift",
        tab2: "Web-development",
        card__title1: "Kursvalut",
        card__subtitle1: "A convenient currency converter, working with data from Russian Central Bank and Forex. The application is written from scratch on UIKit using Storyboards and without third-party libraries. <br /> <br /> You can download exchange rates from several sources. And for storing data offline, was used CoreData. A Pro version is available on StoreKit, which opens up additional features for user comfort.",
        card__button1: "Expand",
        link__title1: "Open Web",
        card__title2: "Project &#171;NFT&#187;",
        card__subtitle2: "Layout of a landing page for a site about NFT. This is my first acquaintance with web layout as such. Here I got acquainted with the basics of layout, worked out and mastered the basic concepts and techniques.",
        card__button2: "Expand",
        link__title2: "Open live demo",
        card__title3: "Online cinema &#171;LiveTV&#187;",
        card__subtitle3: "Landing page layout on the Bootstrap framework. In the course of working with it, I learned various components and styles, such as navigation, buttons, forms, and modals. <br /> <br /> I also got acquainted with the principles of creating adaptive design. I liked the use of Bootstrap's predefined styles and classes, which make it quick and easy to customize the look of elements and add animations. In general, working with Bootstrap has greatly simplified the layout process.",
        card__button3: "Expand",
        link__title3: "Open live demo",
        card__title4: "Sushi shop &#171;Riksha&#187;",
        card__subtitle4: "Landing layout on SASS/SCSS preprocessor. Here I learned how to use powerful features such as variables to make it easier to manage values, mixins to create reusable styles with parameters, and nesting to structure code. <br /> <br /> I also used operators to manipulate property values, which helped create a responsive design. Overall, using SASS/SCSS has greatly improved the efficiency and organization of my landing page layout.",
        card__button4: "Expand",
        link__title4: "Open live demo",
        card__title5: "Bookstore &#171;Pages&#187;",
        card__subtitle5: "Landing layout on the Tailwind framework. Working with this framework allowed me to use a class-centric methodology and quickly apply styles by adding classes to HTML. This ensured a consistent and uniform website design. <br /> <br /> The framework also offers many predefined styles and utilities, as well as custom classes and components that allow you to create a variety of styles without the need for additional CSS code. <br /> <br /> Tailwind has made my workflow much faster.",
        card__button5: "Expand",
        link__title5: "Open live demo",
        quote: "The journey - is the reward",
        switch__title1: "Theme",
        switch__option1: "Light",
        switch__option2: "Dark",
        switch__option3: "System",
        switch__title2: "Language",
        switch__option4: "Russian",
        switch__option5: "English",
        switch__option6: "System",
        tooltip1: "Show on GitHub",
        tooltip2: "Show on GitHub",
        tooltip3: "Show on GitHub",
        tooltip4: "Show on GitHub",
        tooltip5: "Show on GitHub",
        settings: "Settings",
        headline2: "Contact",
        connect__info: "I am open to offers, happy to answer any questions like how I typically develop a website or app, which tools I use or in what timeframe it is possible to realise your project. <br /> <br /> Just send me an email.",
        headlineS: "Hi there!",
        headlineB: "I am Igor Volkov",
        about__text1: `I am an aspiring developer who strives to create functional products with beautiful designs and a clean, minimalistic interface, because I have always been interested in making applications/websites as effective as possible for everyone who uses them. <br /> <br /> I've been growing as a developer every day since I started about two years ago by taking my <a class="about__link" id="about__link1" href="https://www.udemy.com/course/ios-13-app-development-bootcamp/">first course</a> about Swift mobile development.`,
        about__link1: "first course",
        headline3: "My Story",
        about__text2: "I've always loved technology. From a young age, technology has interested me. Most children play video games - I loved playing too, but my interest was not limited to just entertainment. The more I played, the more I wanted to understand how everything works: how to change something on a web page, how to add something of my own. <br /> <br /> I never lost my curiosity, and my interest in technology changed as I expanded my knowledge: from VK wiki-markup to working with website, using HTML/CSS.",
        resume__title: "Igor Volkov",
        resume__subtitle: "iOS Developer",
        resume__headline1: "Contacts",
        resume__headline2: "Schedule",
        schedule__title: "Full-time",
        schedule__subtitle1: "Full working day",
        schedule__subtitle2: "Office",
        resume__headline3: "Age",
        age__title: `<span class="age__title-big">30</span> years`,
        resume__headline4: "Citizenship",
        citizen__title: "Russia",
        resume__headline5: "Address",
        address__title: "Reutov",
        address__subtitle: "Novokosino metro station",
        resume__headline6: "Languages",
        lang__title1: "Russian",
        lang__subtitle1: "Native",
        lang__title2: "English",
        lang__subtitle2: "B2 Upper Intermediate",
        resume__headline7: "Experience",
        expiriense__title1: "July 2021 - present",
        expiriense__text1: "iOS-development",
        expiriense__text2: "pet-projects",
        expiriense__text3: `Completed two of the best courses in iOS development, studied the main components and frameworks: <span class="bold">Storyboards, XIB, UIKit, SwiftUI</span> based on more than <span class="bold">20</span> educational projects;`,
        expiriense__text4: `Created an app from scratch on <span class="bold">Swift (UIKit)</span>, using <span class="bold">MVC</span> template, which receives data from <span class="bold"> JSON (URLSession)</span>, stores in memory (<span class="bold">CoreData</span>), displays (<span class="bold"><span class="breakWord">NSFetchedResultsController</span >, GCD</span>);`,
        expiriense__text5: `Increased the productivity of colleagues by appox 10 minutes/day by saving time on searching exchange rates data. Uploaded the app to <span class="bold">AppStore</span>;`,
        expiriense__text6: `Watch code on GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit" target="_blank"><span class="breakWord">github.com/artexhibit</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a>`,
        expiriense__title2: "November 2019 - present",
        expiriense__text7: `LLC «Free Lines Company»<a class="fact__expiriense-link" href="https://free-lines.ru"><img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a>`,
        expiriense__text8: "Customer acquisition manager",
        expiriense__text9: "Signed at least two new clients per month due to the distribution of time and tasks;",
        expiriense__title3: "Achievements",
        expiriense__text10: "per year 2022",
        expiriense__text11: `Manager of the Year with clients, who paid for an order to a supplier through the company <span class="bold">(18);</span>`,
        expiriense__text12: `Best Acquisition Manager: June, August, September, November <span class="bold">(4).</span>`,
        resume__headline8: "Education",
        education__title1: `Secondary professional education, <br /> part-time <br /> <span class="bold">2022 - present</span>`,
        education__text1: `GBPOU Technological College №21, Moscow<a class="fact__education-link" href="https://tk21.mskobr.ru"><img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        education__text2: `<span class="bold">Faculty:</span> Megadesign`,
        education__text3: `<span class="bold">Specialty:</span> Information systems and programming`,
        education__title2: `Higher education, <br /> full-time <br /><span class="bold">2010 - 2015</span>`,
        education__text4: `Russian State University of Tourism and Service, Moscow<a class="fact__education-link" href="https://rguts.ru"><img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a>`,
        education__text5: `<span class="bold">Faculty:</span> Social Management`,
        education__text6: `<span class="bold">Specialty:</span> Organizational management`,
        resume__headline9: "Advanced training,Cources",
        courses__type1: "Date",
        courses__type2: "Name",
        courses__type3: "Type",
        courses__type4: "Certificate",
        courses__title1: "Grokking Algorithms",
        courses__subtitle1: "Aditya Bhargava",
        courses__text1: "Book",
        courses__text2: "Video lecture",
        courses__text3: "Video lecture",
        resume__headline10: `<span class="">Professional<span> skills`,
        skills__text: "paid more attention during learning",
        resume__headline11: "Portfolio",
        project__text1: "Currency Converter",
        project__text2: "Results",
        project__text3: "Increased colleagues efficiency by reducing the time required for searching of exhange rates data;",
        project__text4: `Deepened knowledge of working with <span class="bold">URLSession</span> и <span class="bold breakWord">CoreData, NSFetchedResultsController;</span>`,
        project__text5: "Mastered the skill of working with AppStore from the moment of creating a developer account till publishing the app;",
        project__text6: `Received more than <span class="bold">150 downloads</span> of the app (for Russia), plus the app was launched about <span class="bold">2.5 times per day</span> (on average, according to Apple).`,
        project__text7: "Custom implementation of a keyboard with numbers and simple computational operations.",
        project__text8: `Stack: <span class="bold">UIKit, Storyboard, XIB, UIBezierPath, CAShapeLayer</span>`,
        project__text9: `Watch code on GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit/CustomNumpad" target="_blank"><span class="breakWord">github.com/artexhibit/CustomNumpad</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        project__text10: "Custom implementation of a pop-up notification from Apple with additional functionality.",
        project__text11: `Stack: <span class="bold">UIKit, Storyboard, XIB</span>`,
        project__text12: `Watch code on GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit/CustomPopup" target="_blank"><span class="breakWord">github.com/artexhibit/CustomPopup</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        project__text13: "Custom implementation of UIDatePicker view with buttons to confirm or cancel an action.",
        project__text14: `Stack: <span class="bold"> UIKit, Storyboard, XIB,<span class="breakWord">UITapGestureRecognizer</span> </span>`,
        project__text15: `Watch code on GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit/CustomUIViewWithDatePicker" target="_blank"><span class="breakWord">github.com/artexhibit/CustomUIViewWithDatePicker</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        resume__headline12: "Qualities",
        projectCard__headline1: "Desire to learn",
        projectCard__text1: `Started in July 2021, for more than 600 days already, I am improving my knowledge in development on a daily basis, studying for 2 hours a day after my main job. <br /> <br />Imagine the benefits I could bring with possibility of doing it all day.`,
        projectCard__headline2: "Initiative",
        projectCard__text2: `Noticing that colleagues were spending a lot of time searching for ruble exchange rate data for calculations, I took the initiative and created an app for that. <br /> <br /> The currency converter saves them about 5-10 minutes a day. And within a month, we receive a decent number!`,
        projectCard__headline3: "Creativity",
        projectCard__text3: `Created my own portfolio website using HTML, CSS and JS from scratch, which is available at<a class="fact__expiriense-link" href="https://igorcodes.ru" target="_blank"><span class= "fact__big-normal--text breakWord">igorcodes.ru</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" / ></a> <br /> <br /> This greatly improved my skills in creating a project structure and the time required for its implementation.`,
        resume__headline13: "About",
        aboutMe__text: `Completed two of the most authoritative courses on iOS development, studying every day within a year. Created 25 educational projects and one pet-project, included in the TOP 30 AppStore by keywords “Central Bank of the Russian Federation”, “Currency Converter”. <br /> <br /> I want to expand my knowledge in iOS-development, because I believe that it is easier to achieve success doing what you like. Ready to complete test tasks. Preferred work format is office, full-time.<br /> <br /> Always in touch on Telegram<a class="fact__expiriense-link" href="https://t.me/artexhib1t" target="_blank"><span class ="fact__big-normal--text">@artexhib1t</span></a> or email me at<a class="fact__expiriense-link" href="mailto:ceo@igorcodes.ru" target="_blank"><span class="fact__big-normal--text breakWord">ceo@igorcodes.ru</span></a>.`,
        downloader__title: "Download the pdf version of my CV",
        dowloader__text1: "Download",
        dowloader__text2: "The values ​​do not match!",
        dowloader__text3: "Enter the captcha",
    },
    ru: {
        title: "Игорь Волков - iOS-разработчик",
        logo__text: "ИВ",
        link1: "Проекты",
        link2: "Обо мне",
        link3: "Резюме",
        link4: "Связаться",
        hamb__title: "Меню",
        name__title: "Игорь Волков",
        name__subtitle: "Расширяя горизонты: мой путь в мире мобильной и веб-разработки",
        headline1: "Проекты",
        tab1: "Свифт",
        tab2: "Веб-разработка",
        card__title1: "Kursvalut",
        card__subtitle1: "Удобный конвертер валют по курсу ЦБ РФ и Форекс. Приложение написано с нуля на UIKit на Storyboard и без использования сторонних библиотек. <br /> <br /> Доступна загрузка курсов валют из нескольких источников. А для хранения данных офлайн используется CoreData. Доступна Про версия на StoreKit, открывающая расширенные возможности.",
        card__button1: "Раскрыть",
        link__title1: "Открыть сайт",
        card__title2: "Проект &#171;NFT&#187;",
        card__subtitle2: "Вёрстка лендинга сайта про NFT. Это моё первое знакомство с веб-версткой как таковой. Здесь я познакомился с основами верстки, отработал и освоил основные концепции, приёмы.",
        card__button2: "Раскрыть",
        link__title2: "Открыть проект",
        card__title3: "Онлайн-кинотеатр &#171;LiveTV&#187;",
        card__subtitle3: "Вёрстка лендинга сайта на фреймворке Bootstrap. В процессе работы с ним я изучил различные компоненты и стили, такие как навигация, кнопки, формы и модальные окна. <br /> <br /> Также я познакомился с принципами создания адаптивного дизайна. Мне понравилось использование готовых стилей и классов Bootstrap, которые позволяют быстро и просто настроить внешний вид элементов и добавить анимации. В целом, работа с Bootstrap значительно упростила процесс верстки.",
        card__button3: "Раскрыть",
        link__title3: "Открыть проект",
        card__title4: "Магазин суши &#171;Riksha&#187;",
        card__subtitle4: "Вёрстка лендинга на препроцессоре SASS/SCSS. Здесь я научился использовать мощные функции, такие как переменные для упрощения управления значениями, миксины для создания переиспользуемых стилей с параметрами, и вложенность для структурирования кода. <br /> <br /> Также я использовал операторы для манипулирования значениями свойств, что помогло создать гибкий дизайн. В целом, использование SASS/SCSS значительно повысило эффективность и организованность моей верстки лендинга.",
        card__button4: "Раскрыть",
        link__title4: "Открыть проект",
        card__title5: "Книжный магазин &#171;Pages&#187;",
        card__subtitle5: "Вёрстка лендинга на фреймворке Tailwind. Работа с данным фреймворком позволила мне использовать класс-центричную методологию и быстро применять стили через добавление классов в HTML. Это обеспечило последовательный и единообразный дизайн веб-сайта. <br /> <br /> Также фреймворк предлагает множество предварительно определенных стилей и утилит, а также настраиваемых классов и компонентов, позволяющих создавать разнообразные стили без необходимости дополнительного CSS-кода. <br /> <br /> Tailwind значительно ускорил мой рабочий процесс.",
        card__button5: "Раскрыть",
        link__title5: "Открыть проект",
        quote: "Путешествие - это награда",
        switch__title1: "Тема",
        switch__option1: "Светлая",
        switch__option2: "Тёмная",
        switch__option3: "Авто",
        switch__title2: "Язык",
        switch__option4: "Русский",
        switch__option5: "Английский",
        switch__option6: "Авто",
        tooltip1: "Открыть на Github",
        tooltip2: "Открыть на Github",
        tooltip3: "Открыть на Github",
        tooltip4: "Открыть на Github",
        tooltip5: "Открыть на Github",
        settings: "Настройки",
        headline2: "Для связи",
        connect__info: "Я открыт к предложениям, рад ответить на любые вопросы, например, как я обычно подхожу к разработке сайта или приложения или какими инструментами, в какой срок можно реализовать ваш проект. <br /> <br /> Просто отправьте мне электронное письмо.",
        headlineS: "Привет!",
        headlineB: "Меня зовут Игорь",
        about__text1: `Я начинающий разработчик, который стремится создавать функциональные продукты с красивым дизайном и чётким, минималистичным интерфейсом, потому как всегда был заинтересован в том, чтобы приложения/веб-сайты были максимально эффективными для всех, кто ими пользуется. <br /> <br /> Я каждый день развиваюсь, как разработчик с тех пор, как около двух лет назад начал с изучения своего <a class="about__link" id="about__link1" href="https://www.udemy.com/course/ios-13-app-development-bootcamp/">первого курса</a> по мобильной разработке на Swift.`,
        about__link1: "первого курса",
        headline3: "Моя история",
        about__text2: "Я всегда любил технологии. Они интересовали меня с юных лет. Большинство детей играют в видеоигры, - я тоже любил играть, но мой интерес не ограничивался только развлечениями. Чем больше я играл, тем больше мне хотелось понять, как всё работает: как поменять что-то на веб-странице, как добавить что-то своё. <br /> <br /> Я никогда не терял своего любопытства, и мой интерес к технологиям менялся по мере того, как я расширял свои знания: от wiki-разметки ВКонтакте до работы с веб-сайтом на HTML/CSS.",
        resume__title: "Игорь Волков",
        resume__subtitle: "iOS Разработчик",
        resume__headline1: "Контакты",
        resume__headline2: "График",
        schedule__title: "Полная занятость",
        schedule__subtitle1: "Полный рабочий день",
        schedule__subtitle2: "Офис",
        resume__headline3: "Возраст",
        age__title: `<span class="age__title-big">30</span> лет`,
        resume__headline4: "Гражданство",
        citizen__title: "Россия",
        resume__headline5: "Адрес",
        address__title: "Реутов",
        address__subtitle: "м. Новокосино",
        resume__headline6: "Языки",
        lang__title1: "Русский",
        lang__subtitle1: "Родной",
        lang__title2: "Английский",
        lang__subtitle2: "B2 Выше среднего",
        resume__headline7: "Опыт работы",
        expiriense__title1: "июль 2021 - н.в.",
        expiriense__text1: "iOS-разработка",
        expiriense__text2: "pet-проекты",
        expiriense__text3: `Завершил два лучших курса по iOS-разработке, изучил основные компоненты и фреймворки: <span class="bold">Storyboards, XIB, UIKit, SwiftUI</span>
        на основе более <span class="bold">20</span>
        учебных проектов;`,
        expiriense__text4: `Написал с нуля приложение на <span class="bold">Swift (UIKit)</span>, используя шаблон <span class="bold">MVC</span>, которое получает данные из <span class="bold">JSON (URLSession)</span>, хранит в памяти (<span class="bold">CoreData</span>), отображает (<span class="bold"><span class="breakWord">NSFetchedResultsController</span>, GCD
        </span>);`,
        expiriense__text5: `Увеличил эффективность работы коллег примерно на 10 минут в день за счёт экономии времени на поиск данных по курсам валют. Выложил приложение в <span class="bold">AppStore</span>;`,
        expiriense__text6: `Посмотреть код на GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit" target="_blank"><span class="breakWord">github.com/artexhibit</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a>`,
        expiriense__title2: "ноябрь 2019 - н.в.",
        expiriense__text7: `ООО «Фри Лайнс Компани»<a class="fact__expiriense-link" href="https://free-lines.ru"><img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a>`,
        expiriense__text8: "Менеджер по привлечению клиентов",
        expiriense__text9: "Привлекал не менее двух новых клиентов в месяц за счёт распределения времени и задач;",
        expiriense__title3: "Достижения",
        expiriense__text10: "за 2022 календарный год",
        expiriense__text11: `Менеджер года по клиентам, оплатившим заказ поставщику через компанию <span class="bold">(18);</span>`,
        expiriense__text12: `Лучший менеджер по привлечению: июнь, август, сентябрь, ноябрь <span class="bold">(4).</span>`,
        resume__headline8: "Образование",
        education__title1: `Среднее профессиональное образование, <br /> очно-заочная форма <br /> <span class="bold">2022 - н.в.</span>`,
        education__text1: `ГБПОУ Технологический колледж №21, Москва<a class="fact__education-link" href="https://tk21.mskobr.ru"><img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        education__text2: `<span class="bold">Факультет:</span> Мегадизайн`,
        education__text3: `<span class="bold">Специальность:</span> Информационные системы и программирование`,
        education__title2: `Высшее образование, <br /> дневная/очная форма <br /><span class="bold">2010 - 2015</span>`,
        education__text4: `Российский государственный университет туризма и сервиса, Москва<a class="fact__education-link" href="https://rguts.ru"><img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a>`,
        education__text5: `<span class="bold">Факультет:</span> Менеджмент в социальной сфере`,
        education__text6: `<span class="bold">Специальность:</span> Менеджмент организации`,
        resume__headline9: "Повышение квалификации, курсы",
        courses__type1: "Дата",
        courses__type2: "Наименование",
        courses__type3: "Тип",
        courses__type4: "Сертификат",
        courses__title1: "Грокаем алгоритмы",
        courses__subtitle1: "Адитья Бхаргава",
        courses__text1: "Книга",
        courses__text2: "Видеолекция",
        courses__text3: "Видеолекция",
        resume__headline10: `<span class="breakWord">Профессиональные<span> навыки`,
        skills__text: "уделено больше внимания во время обучения",
        resume__headline11: "Портфолио",
        project__text1: "Конвертер валют",
        project__text2: "Итоги",
        project__text3: "Увеличил эффективность работы коллег за счет сокращения времени поиска данных по курсам;",
        project__text4: `Углубил знания по работе с <span class="bold">URLSession</span> и <span class="bold breakWord">CoreData, NSFetchedResultsController;</span>`,
        project__text5: "Освоил навык работы с AppStore от момента создания аккаунта разработчика до публикации приложения;",
        project__text6: `Получил более <span class="bold">150 загрузок</span> приложения (для России), а приложение запускается около <span class="bold">2.5 раз за день</span> (в среднем, по информации Apple).`,
        project__text7: "Кастомная реализация клавиатуры с цифрами и простыми вычислительными операциями.",
        project__text8: `Стек: <span class="bold">UIKit, Storyboard, XIB, UIBezierPath, CAShapeLayer</span>`,
        project__text9: `Посмотреть код на GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit/CustomNumpad" target="_blank"><span class="breakWord">github.com/artexhibit/CustomNumpad</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        project__text10: "Кастомная реализация всплывающего уведомления от Apple с доп функционалом.",
        project__text11: `Стек: <span class="bold">UIKit, Storyboard, XIB</span>`,
        project__text12: `Посмотреть код на GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit/CustomPopup" target="_blank"><span class="breakWord">github.com/artexhibit/CustomPopup</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        project__text13: "Кастомная реализация вью с UIDatePicker, кнопками для подтверждения или отмены действия.",
        project__text14: `Стек: <span class="bold"> UIKit, Storyboard, XIB,<span class="breakWord">UITapGestureRecognizer</span> </span>`,
        project__text15: `Посмотреть код на GitHub:<a class="fact__expiriense-link" href="https://github.com/artexhibit/CustomUIViewWithDatePicker" target="_blank"><span class="breakWord">github.com/artexhibit/CustomUIViewWithDatePicker</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /> </a>`,
        resume__headline12: "Качества",
        projectCard__headline1: "Желание учиться",
        projectCard__text1: `Начав в июле 2021 года, вот уже более 600 дней, я ежедневно совершенствую свои знания в разработке, занимаясь от 2 часов в день после основной работы. <br /> <br />Представьте, какую пользу я cмогу принести, если буду заниматься этим целый день.`,
        projectCard__headline2: "Инициативность",
        projectCard__text2: `Заметив, что коллеги тратят много времени на поиск информации о курсе рубля для расчетов, проявил инициативу и создал приложение. <br /> <br /> Конвертер валют экономит им около 5-10 минут в день. А в рамках месяца набегает приличная цифра!`,
        projectCard__headline3: "Креативность",
        projectCard__text3: `С нуля придумал и реализовал на HTML, CSS и JS свой сайт-портфолио, который доступен по адресу<a class="fact__expiriense-link" href="https://igorcodes.ru" target="_blank"><span class="fact__big-normal--text breakWord">igorcodes.ru</span> <img class="link__icon theme-sensitive" src="./assets/images/resume/header/linkLight.svg" alt="link" /></a> <br /> <br /> Это сильно прокачало мои навыки по созданию структуры проекта и времени, необходимого на его реализацию.`,
        resume__headline13: "О себе",
        aboutMe__text: `В течении года завершил два самых авторитетных курса по iOS-разработке, занимаясь каждый день. Создал 25 учебных проектов и один пет-проект, входящий в ТОП-30 AppStore по ключевым словам «ЦБ РФ», «Конвертер Валют». <br /> <br /> Хочу развиваться, как iOS-разработчик, поскольку считаю, что успехов легче добиться в деле, которое по душе. Готов к выполнению тестовых заданий. Предпочитаемый формат работы - офис.<br /> <br /> Всегда на связи в Telegram<a class="fact__expiriense-link" href="https://t.me/artexhib1t" target="_blank"><span class="fact__big-normal--text">@artexhib1t</span></a> или по почте<a class="fact__expiriense-link" href="mailto:ceo@igorcodes.ru" target="_blank"><span class="fact__big-normal--text breakWord">ceo@igorcodes.ru</span></a>.`,
        downloader__title: "Скачайте версию резюме в pdf",
        dowloader__text1: "Загрузить",
        dowloader__text2: "Значения не совпадают!",
        dowloader__text3: "Введите капчу!",
    },
};
