let languageContent = {
    en: {
        logo__text: "IV",
        link1: "Projects",
        link2: "About me",
        link3: "Resume",
        link4: "Contact",
        hamb__title: "Menu",
        name__title: "Игорь Волков",
        name__subtitle: "Expanding Horizons: My Path in the World of Mobile and Web Development",
        headline: "Projects",
        tab1: "Swift",
        tab2: "Web-development",
        card__title1: "Kursvalut",
        card__subtitle1: "A convenient currency converter at the rate of the Central Bank of the Russian Federation and Forex. The application is written from scratch on UIKit on Storyboard and without the use of third-party libraries. <br /> <br /> You can download exchange rates from several sources. And for storing data offline, CoreData is used. A Pro version is available on StoreKit, which opens up advanced features.",
        card__button1: "Expand",
        link__title1: "Open Web",
        card__title2: "Project &#171;NFT&#187;",
        card__subtitle2: "Layout of a landing page for a site about NFT. This is my first acquaintance with web layout as such. Here I got acquainted with the basics of layout, worked out and mastered the basic concepts and techniques.",
        card__button2: "Expand",
        link__title2: "Open on GitHub",
        card__title3: "Online cinema &#171;LiveTV&#187;",
        card__subtitle3: "Landing page layout on the Bootstrap framework. In the course of working with it, I learned various components and styles, such as navigation, buttons, forms, and modals. <br /> <br /> I also got acquainted with the principles of creating adaptive design. I liked the use of Bootstrap's predefined styles and classes, which make it quick and easy to customize the look of elements and add animations. In general, working with Bootstrap has greatly simplified the layout process.",
        card__button3: "Expand",
        link__title3: "Open on GitHub",
        card__title4: "Sushi shop &#171;Riksha&#187;",
        card__subtitle4: "Landing layout on SASS/SCSS preprocessor. Here I learned how to use powerful features such as variables to make it easier to manage values, mixins to create reusable styles with parameters, and nesting to structure code. <br /> <br /> I also used operators to manipulate property values, which helped create a responsive design. Overall, using SASS/SCSS has greatly improved the efficiency and organization of my landing page layout.",
        card__button4: "Expand",
        link__title4: "Open on GitHub",
        card__title5: "Bookstore &#171;Pages&#187;",
        card__subtitle5: "Landing layout on the Tailwind framework. Working with this framework allowed me to use a class-centric methodology and quickly apply styles by adding classes to HTML. This ensured a consistent and uniform website design. <br /> <br /> The framework also offers many predefined styles and utilities, as well as custom classes and components that allow you to create a variety of styles without the need for additional CSS code. <br /> <br /> Tailwind has made my workflow much faster.",
        card__button5: "Expand",
        link__title5: "Open on GitHub",
        quote: "The journey - is the reward",
        switch__title1: "Theme",
        switch__option1: "Light",
        switch__option2: "Dark",
        switch__option3: "System",
        switch__title2: "Language",
        switch__option4: "Russian",
        switch__option5: "English",
        switch__option6: "Auto",
        settings: "Settings",
    },
    ru: {
        logo__text: "ИВ",
        link1: "Проекты",
        link2: "Обо мне",
        link3: "Резюме",
        link4: "Связаться",
        hamb__title: "Меню",
        name__title: "Игорь Волков",
        name__subtitle: "Расширяя горизонты: мой путь в мире мобильной и веб-разработки",
        headline: "Проекты",
        tab1: "Свифт",
        tab2: "Веб-разработка",
        card__title1: "Kursvalut",
        card__subtitle1: "Удобный конвертер валют по курсу ЦБ РФ и Форекс. Приложение написано с нуля на UIKit на Storyboard и без использования сторонних библиотек. <br /> <br /> Доступна загрузка курсов валют из нескольких источников. А для хранения данных офлайн используется CoreData. Доступна Про версия на StoreKit, открывающая расширенные возможности.",
        card__button1: "Раскрыть",
        link__title1: "Открыть сайт",
        card__title2: "Проект &#171;NFT&#187;",
        card__subtitle2: "Вёрстка лендинга сайта про NFT. Это моё первое знакомство с веб-версткой как таковой. Здесь я познакомился с основами верстки, отработал и освоил основные концепции, приёмы.",
        card__button2: "Раскрыть",
        link__title2: "Открыть на GitHub",
        card__title3: "Онлайн-кинотеатр &#171;LiveTV&#187;",
        card__subtitle3: "Вёрстка лендинга сайта на фреймворке Bootstrap. В процессе работы с ним я изучил различные компоненты и стили, такие как навигация, кнопки, формы и модальные окна. <br /> <br /> Также я познакомился с принципами создания адаптивного дизайна. Мне понравилось использование готовых стилей и классов Bootstrap, которые позволяют быстро и просто настроить внешний вид элементов и добавить анимации. В целом, работа с Bootstrap значительно упростила процесс верстки.",
        card__button3: "Раскрыть",
        link__title3: "Открыть на GitHub",
        card__title4: "Магазин суши &#171;Riksha&#187;",
        card__subtitle4: "Вёрстка лендинга на препроцессоре SASS/SCSS. Здесь я научился использовать мощные функции, такие как переменные для упрощения управления значениями, миксины для создания переиспользуемых стилей с параметрами, и вложенность для структурирования кода. <br /> <br /> Также я использовал операторы для манипулирования значениями свойств, что помогло создать гибкий дизайн. В целом, использование SASS/SCSS значительно повысило эффективность и организованность моей верстки лендинга.",
        card__button4: "Раскрыть",
        link__title4: "Открыть на GitHub",
        card__title5: "Книжный магазин &#171;Pages&#187;",
        card__subtitle5: "Вёрстка лендинга на фреймворке Tailwind. Работа с данным фреймворком позволила мне использовать класс-центричную методологию и быстро применять стили через добавление классов в HTML. Это обеспечило последовательный и единообразный дизайн веб-сайта. <br /> <br /> Также фреймворк предлагает множество предварительно определенных стилей и утилит, а также настраиваемых классов и компонентов, позволяющих создавать разнообразные стили без необходимости дополнительного CSS-кода. <br /> <br /> Tailwind значительно ускорил мой рабочий процесс.",
        card__button5: "Раскрыть",
        link__title5: "Открыть на GitHub",
        quote: "Путешествие - это награда",
        switch__title1: "Тема",
        switch__option1: "Светлая",
        switch__option2: "Тёмная",
        switch__option3: "Авто",
        switch__title2: "Язык",
        switch__option4: "Русский",
        switch__option5: "Английский",
        switch__option6: "Авто",
        settings: "Настройки",
    },
};
